// <auto-generated />
namespace Tp1Mod6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tp2Mod6ModificationDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tp2Mod6ModificationDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202009230715329_Tp2Mod6-ModificationDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
